# Generated by Django 4.2.16 on 2024-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterlevel",
            name="location_lat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="waterlevel",
            name="location_lon",
            field=models.FloatField(default=0.0),
        ),
    ]
