# Generated by Django 4.2.16 on 2024-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapboard", "0002_waterlevel_location_lat_waterlevel_location_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                ("x", models.DecimalField(decimal_places=2, max_digits=10)),
                ("y", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dbmsnr", models.IntegerField()),
                ("hzbnr01", models.IntegerField(primary_key=True, serialize=False)),
                ("typ", models.CharField(max_length=255)),
            ],
        ),
    ]
