# Generated by Django 4.2.16 on 2024-12-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapboard', '0002_emergencyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
