# Generated by Django 4.2.16 on 2024-11-27 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapboard", "0002_emergencyreport"),
        ("mapboard", "0003_station"),
    ]

    operations = []
