# Generated by Django 4.2.16 on 2025-01-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapboard', '0003_remove_emergencyreport_region_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapboard.region'),
            preserve_default=False,
        ),
    ]
