# Generated by Django 4.2.16 on 2024-12-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mapboard", "0004_merge_0002_emergencyreport_0003_station"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station",
            options={"verbose_name": "Station", "verbose_name_plural": "Stations"},
        ),
        migrations.RemoveField(
            model_name="station",
            name="hzbnr01",
        ),
        migrations.RemoveField(
            model_name="station",
            name="typ",
        ),
        migrations.RemoveField(
            model_name="station",
            name="x",
        ),
        migrations.RemoveField(
            model_name="station",
            name="y",
        ),
        migrations.AddField(
            model_name="station",
            name="bundesmeldenetz_koordinaten",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Coordinates (BMN)"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="dienststelle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Service Office"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="einheit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Unit"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="exportzeitraum",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Export Period"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="exportzeitreihe",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Export Time Series"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="gewaesser",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Water Body"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="hdnummer",
            field=models.IntegerField(blank=True, null=True, verbose_name="HD Number"),
        ),
        migrations.AddField(
            model_name="station",
            name="hzbnr",
            field=models.IntegerField(blank=True, null=True, verbose_name="HZB Number"),
        ),
        migrations.AddField(
            model_name="station",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="messstelle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Measurement Point"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="messstellenbetreiber",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Operator"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="orogr_einzugsgebiet",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Catchment Area (km²)"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="prognose",
            field=models.BooleanField(default=False, verbose_name="Forecast"),
        ),
        migrations.AddField(
            model_name="station",
            name="sachgebiet",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Field of Expertise"
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="dbmsnr",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="DBMS Number"
            ),
        ),
        migrations.AlterModelTable(
            name="station",
            table="stations",
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "wert",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("einheit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="mapboard.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
                "db_table": "measurements",
            },
        ),
    ]
