# Generated by Django 4.2.16 on 2025-01-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapboard', '0004_alter_emergencyreport_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapboard.region'),
        ),
    ]
